# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-07-21 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_auto_20190717_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursename',
            options={'verbose_name': 'Course'},
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='course',
        ),
        migrations.AddField(
            model_name='instructor',
            name='courses',
            field=models.ManyToManyField(to='instructors.Coursename'),
        ),
    ]
