# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2019-08-25 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_instructor_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('package', models.CharField(max_length=10)),
                ('news_subscribe', models.BooleanField()),
                ('comment', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('date_apply', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
